version: "3"

#volumes:
#  postgres-data:

services:
  client:
    depends_on:
      - server
    links:
      - server
    build:
      target: client
      context: ./client
      dockerfile: client-local-dev.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./client/src:/app/src
    restart: always
    environment:
       - NODE_ENV=development
       - VITE_BACKEND_API_RESOLVE=http://server:3000/

  server:
    depends_on:
      - postgres
    build:
      target: server
      context: ./server
      dockerfile: server-local-dev.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server/src:/app/src
    restart: always
    environment:
      - NODE_ENV=development

  postgres:
    image: postgres:15
    restart: always
    user: 1000:1000
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_DB: test_db
    volumes:
      #- postgres-data:/var/lib/postgresql /data
      - ./storage-data/test-postgres:/var/lib/postgresql/data

