version: "3"

services:
  client:
    depends_on:
      - server
    links:
      - server
    build:
      target: client
      context: ./client
      dockerfile: client-prod.Dockerfile
    ports:
      - "8080:80"
    restart: always
    environment:
       - NODE_ENV=production

  server:
    depends_on:
      - postgres
    build:
      target: server
      context: ./server
      dockerfile: server-prod.Dockerfile
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production

  postgres:
    image: postgres:15
    restart: always
    user: 1000:1000
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_DB: test_db
    volumes:
      - ./storage-data/test-postgres:/var/lib/postgresql/data
